### ISSUE TITLE
Read Only Deploy Key für Server erstellen

### ISSUE THREAD

**Issue by ak1898** [adlerhurst/just-one-digital#17]
@adlerhurst 

Für den Server benötigen wir einen Read Only Deploy Key. mit diesem Key können wir das Repo von Github auf den Server pullen und müssen dabei keinen Benutzer mit Schreibrechten verwenden.

https://github.blog/2015-06-16-read-only-deploy-keys/

**Comment by adlerhurst** [comment]
Ich verstehe noch nicht welches problem wir damit lösen wollen. Nur weil irgendwas via ssh auf unser repo zugreifen kann, weiss es noch nicht was es das soll. Ci-ops startet in der pipeline und diese kann aktuell nichts triggern
